[web]
address = ":4040"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":4848"

[file]

[backends]
  [backends.chatapp]
    [backends.chatapp.servers.server1]
    url = "http://127.0.0.1:8080"
  [backends.chatapp_api]
    [backends.chatapp_api.servers.server1]
    url = "http://127.0.0.1:3000"

[frontends]
  [frontends.chatapp_api]
  backend = "chatapp_api"
  passHostHeader = true
  [frontends.chatapp_api.routes.api_ask]
  rule = "PathPrefixStrip:/api"

  [frontends.chatapp]
  backend = "chatapp"
  passHostHeader = true
